##
# (C) Tenable, Inc.
#
# The package checks in this plugin were extracted from
# SUSE update advisory SUSE-SU-2022:1751-1. The text itself
# is copyright (C) SUSE.
##

include('compat.inc');

if (description)
{
  script_id(161400);
  script_version("1.3");
  script_set_attribute(attribute:"plugin_modification_date", value:"2023/03/10");

  script_cve_id(
    "CVE-2021-0071",
    "CVE-2021-26312",
    "CVE-2021-26339",
    "CVE-2021-26342",
    "CVE-2021-26347",
    "CVE-2021-26348",
    "CVE-2021-26349",
    "CVE-2021-26350",
    "CVE-2021-26364",
    "CVE-2021-26372",
    "CVE-2021-26373",
    "CVE-2021-26375",
    "CVE-2021-26376",
    "CVE-2021-26378",
    "CVE-2021-26388",
    "CVE-2021-33139",
    "CVE-2021-33155",
    "CVE-2021-46744"
  );
  script_xref(name:"SuSE", value:"SUSE-SU-2022:1751-1");

  script_name(english:"SUSE SLES15 Security Update : kernel-firmware (SUSE-SU-2022:1751-1)");

  script_set_attribute(attribute:"synopsis", value:
"The remote SUSE host is missing one or more security updates.");
  script_set_attribute(attribute:"description", value:
"The remote SUSE Linux SLES15 host has packages installed that are affected by multiple vulnerabilities as referenced in
the SUSE-SU-2022:1751-1 advisory.

  - Improper input validation in firmware for some Intel(R) PROSet/Wireless WiFi in UEFI may allow an
    unauthenticated user to potentially enable escalation of privilege via adjacent access. (CVE-2021-0071)

  - Failure to flush the Translation Lookaside Buffer (TLB) of the I/O memory management unit (IOMMU) may lead
    an IO device to write to memory it should not be able to access, resulting in a potential loss of
    integrity. (CVE-2021-26312, CVE-2021-26348)

  - A bug in AMD CPU's core logic may allow for an attacker, using specific code from an unprivileged VM, to
    trigger a CPU core hang resulting in a potential denial of service. AMD believes the specific code
    includes a specific x86 instruction sequence that would not be generated by compilers. (CVE-2021-26339)

  - In SEV guest VMs, the CPU may fail to flush the Translation Lookaside Buffer (TLB) following a particular
    sequence of operations that includes creation of a new virtual machine control block (VMCB). The failure
    to flush the TLB may cause the microcode to use stale TLB translations which may allow for disclosure of
    SEV guest memory contents. Users of SEV-ES/SEV-SNP guest VMs are not impacted by this vulnerability.
    (CVE-2021-26342)

  - Failure to validate the integer operand in ASP (AMD Secure Processor) bootloader may allow an attacker to
    introduce an integer overflow in the L2 directory table in SPI flash resulting in a potential denial of
    service. (CVE-2021-26347)

  - Failure to assign a new report ID to an imported guest may potentially result in an SEV-SNP guest VM being
    tricked into trusting a dishonest Migration Agent (MA). (CVE-2021-26349)

  - A TOCTOU race condition in SMU may allow for the caller to obtain and manipulate the address of a message
    port register which may result in a potential denial of service. (CVE-2021-26350)

  - Insufficient bounds checking in an SMU mailbox register could allow an attacker to potentially read
    outside of the SRAM address range which could result in an exception handling leading to a potential
    denial of service. (CVE-2021-26364)

  - Insufficient bound checks related to PCIE in the System Management Unit (SMU) may result in access to an
    invalid address space that could result in denial of service. (CVE-2021-26372)

  - Insufficient bound checks in the System Management Unit (SMU) may result in a system voltage malfunction
    that could result in denial of resources and/or possibly denial of service. (CVE-2021-26373)

  - Insufficient General Purpose IO (GPIO) bounds check in System Management Unit (SMU) may result in
    access/updates from/to invalid address space that could result in denial of service. (CVE-2021-26375)

  - Insufficient checks in System Management Unit (SMU) FeatureConfig may result in reenabling features
    potentially resulting in denial of resources and/or denial of service. (CVE-2021-26376)

  - Insufficient bound checks in the System Management Unit (SMU) may result in access to an invalid address
    space that could result in denial of service. (CVE-2021-26378)

  - Improper validation of the BIOS directory may allow for searches to read beyond the directory table copy
    in RAM, exposing out of bounds memory contents, resulting in a potential denial of service.
    (CVE-2021-26388)

  - Improper conditions check in firmware for some Intel(R) Wireless Bluetooth(R) and Killer(TM) Bluetooth(R)
    products before version 22.100 may allow an authenticated user to potentially enable denial of service via
    adjacent access. (CVE-2021-33139)

  - Improper input validation in firmware for some Intel(R) Wireless Bluetooth(R) and Killer(TM) Bluetooth(R)
    products before version 22.100 may allow an authenticated user to potentially enable denial of service via
    adjacent access. (CVE-2021-33155)

  - An attacker with access to a malicious hypervisor may be able to infer data values used in a SEV guest on
    AMD CPUs by monitoring ciphertext values over time. (CVE-2021-46744)

Note that Nessus has not tested for these issues but has instead relied only on the application's self-reported version
number.");
  script_set_attribute(attribute:"see_also", value:"https://bugzilla.suse.com/1192953");
  script_set_attribute(attribute:"see_also", value:"https://bugzilla.suse.com/1195786");
  script_set_attribute(attribute:"see_also", value:"https://bugzilla.suse.com/1199459");
  script_set_attribute(attribute:"see_also", value:"https://bugzilla.suse.com/1199470");
  # https://lists.suse.com/pipermail/sle-security-updates/2022-May/011100.html
  script_set_attribute(attribute:"see_also", value:"http://www.nessus.org/u?dbc99f7f");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-0071");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26312");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26339");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26342");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26347");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26348");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26349");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26350");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26364");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26372");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26373");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26375");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26376");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26378");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-26388");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-33139");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-33155");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2021-46744");
  script_set_attribute(attribute:"solution", value:
"Update the affected kernel-firmware and / or ucode-amd packages.");
  script_set_cvss_base_vector("CVSS2#AV:A/AC:L/Au:N/C:P/I:P/A:P");
  script_set_cvss_temporal_vector("CVSS2#E:U/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:A/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:U/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2021-0071");

  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");

  script_set_attribute(attribute:"vuln_publication_date", value:"2021/11/16");
  script_set_attribute(attribute:"patch_publication_date", value:"2022/05/19");
  script_set_attribute(attribute:"plugin_publication_date", value:"2022/05/20");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:kernel-firmware");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:ucode-amd");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:novell:suse_linux:15");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_family(english:"SuSE Local Security Checks");

  script_copyright(english:"This script is Copyright (C) 2022-2023 and is owned by Tenable, Inc. or an Affiliate thereof.");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/cpu", "Host/SuSE/release", "Host/SuSE/rpm-list");

  exit(0);
}


include('rpm.inc');

if (!get_kb_item('Host/local_checks_enabled')) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
var os_release = get_kb_item("Host/SuSE/release");
if (isnull(os_release) || os_release !~ "^(SLED|SLES)") audit(AUDIT_OS_NOT, "SUSE");
var os_ver = pregmatch(pattern: "^(SLE(S|D)\d+)", string:os_release);
if (isnull(os_ver)) audit(AUDIT_UNKNOWN_APP_VER, 'SUSE');
os_ver = os_ver[1];
if (! preg(pattern:"^(SLES15)$", string:os_ver)) audit(AUDIT_OS_NOT, 'SUSE SLES15', 'SUSE (' + os_ver + ')');

if (!get_kb_item("Host/SuSE/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

var cpu = get_kb_item('Host/cpu');
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if ('x86_64' >!< cpu && cpu !~ "^i[3-6]86$" && 's390' >!< cpu && 'aarch64' >!< cpu) audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, 'SUSE (' + os_ver + ')', cpu);

var service_pack = get_kb_item("Host/SuSE/patchlevel");
if (isnull(service_pack)) service_pack = "0";
if (os_ver == "SLES15" && (! preg(pattern:"^(1|2)$", string:service_pack))) audit(AUDIT_OS_NOT, "SLES15 SP1/2", os_ver + " SP" + service_pack);

var pkgs = [
    {'reference':'kernel-firmware-20200107-150100.3.31.1', 'sp':'1', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_BCL-release-15.1', 'SLES_SAP-release-15.1', 'SLE_HPC-ESPOS-release-1']},
    {'reference':'ucode-amd-20200107-150100.3.31.1', 'sp':'1', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_BCL-release-15.1', 'SLES_SAP-release-15.1', 'SLE_HPC-ESPOS-release-1']},
    {'reference':'kernel-firmware-20200107-150100.3.31.1', 'sp':'2', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_BCL-release-15.2', 'SLES_SAP-release-15.2', 'SLE_HPC-ESPOS-release-2']},
    {'reference':'ucode-amd-20200107-150100.3.31.1', 'sp':'2', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_BCL-release-15.2', 'SLES_SAP-release-15.2', 'SLE_HPC-ESPOS-release-2']},
    {'reference':'kernel-firmware-20200107-150100.3.31.1', 'sp':'1', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.1', 'sles-ltss-release-15.1']},
    {'reference':'ucode-amd-20200107-150100.3.31.1', 'sp':'1', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.1', 'sles-ltss-release-15.1']},
    {'reference':'kernel-firmware-20200107-150100.3.31.1', 'sp':'2', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.2', 'sles-ltss-release-15.2']},
    {'reference':'ucode-amd-20200107-150100.3.31.1', 'sp':'2', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.2', 'sles-ltss-release-15.2']}
];

var ltss_caveat_required = FALSE;
var flag = 0;
foreach var package_array ( pkgs ) {
  var reference = NULL;
  var _release = NULL;
  var sp = NULL;
  var _cpu = NULL;
  var exists_check = NULL;
  var rpm_spec_vers_cmp = NULL;
  if (!empty_or_null(package_array['reference'])) reference = package_array['reference'];
  if (!empty_or_null(package_array['release'])) _release = package_array['release'];
  if (!empty_or_null(package_array['sp'])) sp = package_array['sp'];
  if (!empty_or_null(package_array['cpu'])) _cpu = package_array['cpu'];
  if (!empty_or_null(package_array['exists_check'])) exists_check = package_array['exists_check'];
  if (!empty_or_null(package_array['rpm_spec_vers_cmp'])) rpm_spec_vers_cmp = package_array['rpm_spec_vers_cmp'];
  if (reference && _release) {
    if (exists_check) {
      var check_flag = 0;
      foreach var check (exists_check) {
        if (!rpm_exists(release:_release, rpm:check)) continue;
        if ('ltss' >< tolower(check)) ltss_caveat_required = TRUE;
        check_flag++;
      }
      if (!check_flag) continue;
    }
    if (rpm_check(release:_release, sp:sp, cpu:_cpu, reference:reference, rpm_spec_vers_cmp:rpm_spec_vers_cmp)) flag++;
  }
}

if (flag)
{
  var ltss_plugin_caveat = NULL;
  if(ltss_caveat_required) ltss_plugin_caveat = '\n' +
    'NOTE: This vulnerability check contains fixes that apply to\n' +
    'packages only available in SUSE Enterprise Linux Server LTSS\n' +
    'repositories. Access to these package security updates require\n' +
    'a paid SUSE LTSS subscription.\n';
  security_report_v4(
      port       : 0,
      severity   : SECURITY_WARNING,
      extra      : rpm_report_get() + ltss_plugin_caveat
  );
  exit(0);
}
else
{
  var tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, 'kernel-firmware / ucode-amd');
}
