#
# (C) Tenable Network Security, Inc.
#
# The descriptive text and package checks in this plugin were
# extracted from openSUSE Security Update openSUSE-2020-1475.
#
# The text description of this plugin is (C) SUSE LLC.
#

include("compat.inc");

if (description)
{
  script_id(140741);
  script_version("1.3");
  script_set_attribute(attribute:"plugin_modification_date", value:"2022/05/13");

  script_cve_id("CVE-2019-10067", "CVE-2019-12248", "CVE-2019-12497", "CVE-2019-12746", "CVE-2019-13457", "CVE-2019-13458", "CVE-2019-16375", "CVE-2019-18179", "CVE-2019-18180", "CVE-2019-9752", "CVE-2019-9892", "CVE-2020-1765", "CVE-2020-1766", "CVE-2020-1769", "CVE-2020-1770", "CVE-2020-1771", "CVE-2020-1772", "CVE-2020-1773");

  script_name(english:"openSUSE Security Update : otrs (openSUSE-2020-1475)");
  script_summary(english:"Check for the openSUSE-2020-1475 patch");

  script_set_attribute(
    attribute:"synopsis",
    value:"The remote openSUSE host is missing a security update."
  );
  script_set_attribute(
    attribute:"description",
    value:
"Otrs was updated to 5.0.42, fixing lots of bugs and security issues :

https://community.otrs.com/otrs-community-edition-5s-patch-level-42/

  - CVE-2020-1773 boo#1168029 OSA-2020-10 :

  - Session / Password / Password token leak An attacker
    with the ability to generate session IDs or password
    reset tokens, either by being able to authenticate or by
    exploiting OSA-2020-09, may be able to predict other
    users session IDs, password reset tokens and
    automatically generated passwords.

  - CVE-2020-1772 boo#1168029 OSA-2020-09 :

  - Information Disclosure It&rsquo;s possible to craft Lost
    Password requests with wildcards in the Token value,
    which allows attacker to retrieve valid Token(s),
    generated by users which already requested new
    passwords.

  - CVE-2020-1771 boo#1168030 OSA-2020-08 :

  - Possible XSS in Customer user address book Attacker is
    able craft an article with a link to the customer
    address book with malicious content (JavaScript). When
    agent opens the link, JavaScript code is executed due to
    the missing parameter encoding.

  - CVE-2020-1770 boo#1168031 OSA-2020-07 :

  - Information disclosure in support bundle files Support
    bundle generated files could contain sensitive
    information that might be unwanted to be disclosed.

  - CVE-2020-1769 boo#1168032 OSA-2020-06 :

  - Autocomplete in the form login screens In the login
    screens (in agent and customer interface), Username and
    Password fields use autocomplete, which might be
    considered as security issue.

Update to 5.0.41
https://community.otrs.com/otrs-community-edition-5s-patch-level-41/

  - bug#14912 - Installer refers to non-existing
    documentation

  - added code to upgrade OTRS from 4 to 5

    READ UPGRADING.SUSE

  - steps 1 to 4 are done by rpm pkg

  - steps 5 to *END* need to be done manually cause of DB
    backup

Update to 5.0.40

https://community.otrs.com/otrs-community-edition-5s-patch-level-40/

  - CVE-2020-1766 boo#1160663 OSA-2020-02: Improper handling
    of uploaded inline images Due to improper handling of
    uploaded images it is possible in very unlikely and rare
    conditions to force the agents browser to execute
    malicious JavaScript from a special crafted SVG file
    rendered as inline jpg file.

  - CVE-2020-1765, OSA-2020-01: Spoofing of From field in
    several screens An improper control of parameters allows
    the spoofing of the from fields of the following
    screens: AgentTicketCompose, AgentTicketForward,
    AgentTicketBounce and AgentTicketEmailOutbound

  - run bin/otrs.Console.pl Maint::Config::Rebuild after the
    upgrade

  - Update 5.0.39
    https://community.otrs.com/otrs-community-edition-5s-pat
    ch-level-39/

  - CVE-2019-18180 boo#1157001 OSA-2019-15: Denial of
    service OTRS can be put into an endless loop by
    providing filenames with overly long extensions. This
    applies to the PostMaster (sending in email) and also
    upload (attaching files to mails, for example).

  - CVE-2019-18179 OSA-2019-14: Information Disclosure An
    attacker who is logged into OTRS as an agent is able to
    list tickets assigned to other agents, which are in the
    queue where attacker doesn&rsquo;t have permissions.

Update to 5.0.38
https://community.otrs.com/release-notes-otrs-5s-patch-level-38/

  - CVE-2019-16375, boo#1156431 OSA-2019-13: Stored XXS An
    attacker who is logged into OTRS as an agent or customer
    user with appropriate permissions can create a carefully
    crafted string containing malicious JavaScript code as
    an article body. This malicious code is executed when an
    agent compose an answer to the original article.

Update to 5.0.37
https://community.otrs.com/release-notes-otrs-5s-patch-level-37/

  - CVE-2019-13458, boo#1141432, OSA-2019-12 :

    Information Disclosure An attacker who is logged into
    OTRS as an agent user with appropriate permissions can
    leverage OTRS tags in templates in order to disclose
    hashed user passwords.

  - CVE-2019-13457, boo#1141431, OSA-2019-11 :

    Information Disclosure A customer user can use the
    search results to disclose information from their
    &ldquo;company&rdquo; tickets (with the same
    CustomerID), even when
    CustomerDisableCompanyTicketAccess setting is turned on.

  - CVE-2019-12746, boo#1141430, OSA-2019-10 :

    Session ID Disclosure A user logged into OTRS as an
    agent might unknowingly disclose their session ID by
    sharing the link of an embedded ticket article with
    third parties. This identifier can be then potentially
    abused in order to impersonate the agent user.

Update to 5.0.36

https://community.otrs.com/release-notes-otrs-5s-patch-level-36/

  - CVE-2019-12497, boo#1137614, OSA-2019-09: Information
    Disclosure In the customer or external frontend,
    personal information of agents can be disclosed like
    Name and mail address in external notes.

  - CVE-2019-12248, boo#1137615, OSA-2019-08: Loading
    External Image Resources An attacker could send a
    malicious email to an OTRS system. If a logged in agent
    user quotes it, the email could cause the browser to
    load external image resources.

Update to 5.0.35

https://community.otrs.com/release-notes-otrs-5s-patch-level-35/

  - CVE-2019-10067, boo#1139406, OSA-2019-05 :

    Reflected and Stored XSS An attacker who is logged into
    OTRS as an agent user with appropriate permissions may
    manipulate the URL to cause execution of JavaScript in
    the context of OTRS.

  - CVE-2019-9892, boo#1139406, OSA-2019-04 :

    XXE Processing An attacker who is logged into OTRS as an
    agent user with appropriate permissions may try to
    import carefully crafted Report Statistics XML that will
    result in reading of arbitrary files of OTRS filesystem.

  - update missing CVE for OSA-2018-10, OSA-2019-01

Update to 5.0.34

- https://community.otrs.com/release-notes-otrs-5s-patch-level-34/

  - CVE-2019-9752, boo#1122560, OSA-2019-01: Stored XSS An
    attacker who is logged into OTRS as an agent or a
    customer user may upload a carefully crafted resource in
    order to cause execution of JavaScript in the context of
    OTRS.

Update to 5.0.33

- https://community.otrs.com/release-notes-otrs-5s-patch-level-33/

Update to 5.0.26

- https://www.otrs.com/release-notes-otrs-5s-patch-level-26

- https://www.otrs.com/release-notes-otrsitsm-module-5s-patch-level-26/

  - remove obsolete

  - otrs-scheduler.service

  - otrs-scheduler.init This update was imported from the
    openSUSE:Leap:15.1:Update update project."
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1122560"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1137614"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1137615"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1139406"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1141430"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1141431"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1141432"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1156431"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1157001"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1160663"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1168029"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1168030"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1168031"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1168032"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/otrs-community-edition-5s-patch-level-39/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/otrs-community-edition-5s-patch-level-40/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/otrs-community-edition-5s-patch-level-41/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/otrs-community-edition-5s-patch-level-42/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/release-notes-otrs-5s-patch-level-33/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/release-notes-otrs-5s-patch-level-34/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/release-notes-otrs-5s-patch-level-35/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/release-notes-otrs-5s-patch-level-36/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/release-notes-otrs-5s-patch-level-37/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://community.otrs.com/release-notes-otrs-5s-patch-level-38/"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://www.otrs.com/release-notes-otrs-5s-patch-level-26"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://www.otrs.com/release-notes-otrsitsm-module-5s-patch-level-26/"
  );
  script_set_attribute(attribute:"solution", value:"Update the affected otrs packages.");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:S/C:P/I:P/A:N");
  script_set_cvss_temporal_vector("CVSS2#E:U/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:U/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2020-1773");
  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:otrs");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:otrs-itsm");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:novell:opensuse:15.1");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:novell:opensuse:15.2");

  script_set_attribute(attribute:"vuln_publication_date", value:"2019/03/13");
  script_set_attribute(attribute:"patch_publication_date", value:"2020/09/19");
  script_set_attribute(attribute:"plugin_publication_date", value:"2020/09/23");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2020-2022 and is owned by Tenable, Inc. or an Affiliate thereof.");
  script_family(english:"SuSE Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/SuSE/release", "Host/SuSE/rpm-list");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");

if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
release = get_kb_item("Host/SuSE/release");
if (isnull(release) || release =~ "^(SLED|SLES)") audit(AUDIT_OS_NOT, "openSUSE");
if (release !~ "^(SUSE15\.1|SUSE15\.2)$") audit(AUDIT_OS_RELEASE_NOT, "openSUSE", "15.1 / 15.2", release);
if (!get_kb_item("Host/SuSE/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);



flag = 0;

if ( rpm_check(release:"SUSE15.1", reference:"otrs-6.0.29-lp151.2.6.2") ) flag++;
if ( rpm_check(release:"SUSE15.1", reference:"otrs-itsm-6.0.29-lp151.2.6.2") ) flag++;
if ( rpm_check(release:"SUSE15.2", reference:"otrs-6.0.29-lp152.2.3.4") ) flag++;
if ( rpm_check(release:"SUSE15.2", reference:"otrs-itsm-6.0.29-lp152.2.3.4") ) flag++;

if (flag)
{
  if (report_verbosity > 0) security_warning(port:0, extra:rpm_report_get());
  else security_warning(0);
  exit(0);
}
else
{
  tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, "otrs / otrs-itsm");
}
