#%NASL_MIN_LEVEL 80900
##
# (C) Tenable, Inc.
##

include('compat.inc');

if (description)
{
  script_id(168926);
  script_version("1.2");
  script_set_attribute(attribute:"plugin_modification_date", value:"2022/12/20");

  script_cve_id(
    "CVE-2020-26870",
    "CVE-2022-25647",
    "CVE-2022-34169",
    "CVE-2022-46675",
    "CVE-2022-46676",
    "CVE-2022-46677",
    "CVE-2022-46678",
    "CVE-2022-46754",
    "CVE-2022-46755"
  );
  script_xref(name:"CEA-ID", value:"CEA-2021-0001");

  script_name(english:"Dell Wyse Management Suite < 4.0 Multiple Vulnerabilities (DSA-2022-329)");

  script_set_attribute(attribute:"synopsis", value:
"Dell Wyse Management Suite installed on the local host is affected by multiple vulnerabilities.");
  script_set_attribute(attribute:"description", value:
"The version of Dell Wyse Management Suite installed on the remote host is prior to 4.0. It is, therefore, affected by
multiple vulnerabilities as referenced in the DSA-2022-329 advisory.

  - Cure53 DOMPurify before 2.0.17 allows mutation XSS. This occurs because a serialize-parse roundtrip does
    not necessarily return the original DOM tree, and a namespace can change from HTML to MathML, as
    demonstrated by nesting of FORM elements. (CVE-2020-26870)

  - The package com.google.code.gson:gson before 2.8.9 are vulnerable to Deserialization of Untrusted Data via
    the writeReplace() method in internal classes, which may lead to DoS attacks. (CVE-2022-25647)

  - The Apache Xalan Java XSLT library is vulnerable to an integer truncation issue when processing malicious
    XSLT stylesheets. This can be used to corrupt Java class files generated by the internal XSLTC compiler
    and execute arbitrary Java bytecode. The Apache Xalan Java project is dormant and in the process of being
    retired. No future releases of Apache Xalan Java to address this issue are expected. Note: Java runtimes
    (such as OpenJDK) include repackaged copies of Xalan. (CVE-2022-34169)

  - Wyse Management Suite Repository 3.8 and earlier contain an information disclosure vulnerability in error
    pages with which an attacker may potentially discover the internal structure of the application and its
    components and use this information for further vulnerability research. (CVE-2022-46675)

  - Wyse Management Suite 3.8 and earlier contain an improper access control vulnerability. A malicious admin
    user may potentially disable or delete users under administration and unassigned admins for which the
    group admin is not authorized. (CVE-2022-46676)

  - Wyse Management Suite 3.8 and earlier contain an improper access control vulnerability. An authenticated
    malicious admin user may potentially create a subgroup under a group for which the admin is not
    authorized. (CVE-2022-46677)

  - Wyse Management Suite 3.8 and earlier contain an improper access control vulnerability. An authenticated
    malicious admin user may potentially edit general client policy for which the user is not authorized.
    (CVE-2022-46678, CVE-2022-46755)

  - Wyse Management Suite 3.8 and earlier contain an improper access control vulnerability. An authenticated
    malicious admin user may potentially access certain pro license features for which this admin is not
    authorized in order to configure user controlled external entities. (CVE-2022-46754)

Note that Nessus has not tested for these issues but has instead relied only on the application's self-reported version
number.");
  # https://www.dell.com/support/kbdoc/en-us/000206134/dsa-2022-329-dell-wyse-management-suite-security-update-for-multiple-vulnerabilities
  script_set_attribute(attribute:"see_also", value:"http://www.nessus.org/u?e53e2c78");
  script_set_attribute(attribute:"solution", value:
"Upgrade to Dell Wyse Management Suite version 4.0 or later.");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:M/Au:N/C:N/I:P/A:N");
  script_set_cvss_temporal_vector("CVSS2#E:POC/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:P/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2020-26870");
  script_set_attribute(attribute:"cvss3_score_source", value:"CVE-2022-34169");

  script_set_attribute(attribute:"exploitability_ease", value:"Exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"true");

  script_set_attribute(attribute:"vuln_publication_date", value:"2020/10/07");
  script_set_attribute(attribute:"patch_publication_date", value:"2022/12/19");
  script_set_attribute(attribute:"plugin_publication_date", value:"2022/12/19");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"cpe:/a:dell:wyse_management_suite");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_family(english:"Windows");

  script_copyright(english:"This script is Copyright (C) 2022 and is owned by Tenable, Inc. or an Affiliate thereof.");

  script_dependencies("dell_wyse_management_suite_win_installed.nbin");
  script_require_keys("installed_sw/Dell Wyse Management Suite");

  exit(0);
}

include('vcf.inc');
var app_info = vcf::get_app_info(app:'Dell Wyse Management Suite', win_local:TRUE);
var constraints = [
  { 'fixed_version' : '4.0' }
];
vcf::check_version_and_report(
    app_info:app_info,
    constraints:constraints,
    severity:SECURITY_WARNING,
    flags:{'xss':TRUE}
);
